### ISSUE TITLE
AttributeError: 'API' object has no attribute 'get_history'

### ISSUE THREAD

**Issue by mehedi02** [hootnot/oanda-api-v20#143]
#**Following code produce AttributeError**

import configparser
import oandapyV20 as opy
import pandas as pd

config = configparser.ConfigParser()
config.read('oanda.cfg')

oanda = opy.API(environment='practice', access_token=config['oanda']['access_token'])

data = oanda.get_historyV20(instrument='EUR_USD', start='2016-12-08', end='2016-12-10', granularity='M1')

df = pd.DataFrame(data['candles']).set_index('time')

df.index = pd.DatetimeIndex(df.index)

df.info()

**Comment by hootnot** [comment]
@mehedi02 

it looks like you mixup my library (oandapyV20) and the one of Oanda (v20).

Using oandapyV20 you create request instances and process these using the client (the oanda instance in your example). So instead of your 'data-line' create the request and process it like:

```
# see: http://developer.oanda.com/rest-live-v20/instrument-ep/
params = { 'from': ...,
 'to': ... ,
 'granularity': 
}
r = instruments.InstrumentsCandles(instrument="EUR_USD", params=params)
oanda.request(r)
print r.response['candles']
```

take a look at the docs: https://oanda-api-v20.readthedocs.io/en/latest/endpoints/instruments/instrumentlist.html

**Comment by mehedi02** [comment]
Thank you for your reply

**Comment by hootnot** [comment]
Hi,

Since you were playing with historical data and dataframes you might want to take a look at:
#104
