### ISSUE TITLE
Failed to establish a new connection: [Errno -2] Name or service not known'

### ISSUE THREAD

**Issue by biographie** [hootnot/oanda-api-v20#174]
I am getting this error for some reason

ConnectionError: HTTPSConnectionPool(host='%09api-fxpractice.oanda.com', port=443): Max retries exceeded with url: /v3/accounts/101-004-16983542-001/instruments/GBP_JPY/candles?from=1546293600.0&to=1577829600.0&granularity=D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0e2ea016d8>: Failed to establish a new connection: [Errno -2] Name or service not known',))

Could anyone tell me how to fix this problem?

**Comment by hootnot** [comment]
Pls check their website. Probably a maintenance weekend. When the perform maintenance there can be downtime for hours or even the whole weekend. 
At sunday 21:00 UTC you should not experience problems anymore because markets will open.

(my personal experience at market close yesterday was, that services were not available shortly after market close)

**Comment by biographie** [comment]
Thanks for the response. Okay I will try again on Sunday. 
Could this potentially be because I had too many connections open and forgot to close them and thus limited my API access?

**Comment by hootnot** [comment]
I see a %09 in the host, that is a horizontal tab. That should not be there. My conclusion is that you didn't use oandapyV20 in this case. But regardless the way you want to access OANDA : if they have maintenance, ConnectionErrors can occur.
Too many open ? Pls check the limits they have on developer.oanda.com for limits.

Just checked some connectivity on both live and practice environments: I have no issues currently
