### ISSUE TITLE
CALENDAR's class arguments 

### ISSUE THREAD

**Issue by msh855** [hootnot/oanda-api-v20#214]
Hello, 

I am trying to use this [example](https://oanda-api-v20.readthedocs.io/en/latest/endpoints/forexlabs/calendar.html): 

But your documentation for the argument `params` points to OANDA's documentation, which in turn has no information as its page is not working for forexlabs: https://developer.oanda.com/rest-live-v20/forexlabs-ep/ 

```
params =
        {
          "instrument": "EUR_USD",
          "period": 86400
        }

```
It looks that the `params` takes two inputs. First input, that is `instrument` is ok. I can understand what values takes. But I do not understand what values the second input takes, that is the`period`. 

Any help ?

**Comment by hootnot** [comment]
I think that endpoint has been deleted.
Forex labs was in V1. When OANDA released V20 there were some forexlabs related endpoints that were 'to come'.
For some time the old V1 endpoints were supported, but in the end the endpoints were dropped.

In a next release I will drop these classes, since the endpoints do not exist anymore.
